image: gcc

before_script:
    - apt-get update
    - apt-get -y install cmake
    - apt-get -y install python3 python3-pip
    - pip install conan
    

stages:
  - configure
  - build
  - test

configurestuff:
  stage: configure
  script:
   - mkdir build
   - cd build
   - conan install ..
   - cmake ..
  artifacts:
    paths:
     - build

buildstuff:
  stage: build
  script:
   - cd build
   - cmake --build .
  artifacts:
    paths:
     - build
  dependencies:
    - configurestuff

teststuff:
  stage: test
  script:
   - ls -R
   - cd build
   - ctest . -C Debug
  artifacts:
    paths:
     - build
  dependencies:
    - buildstuff