image: conanio/gcc11-ubuntu16.04

before_script:
    - cmake --version
    - conan --version
    - conan remote add gitlab ${CI_API_V4_URL}/projects/10/packages/conan
    - conan user gitlab+deploy-token-2 --remote gitlab -p ${CI_JOB_TOKEN}

stages:
  - configure
  - build
  - test

configurestuff:
  stage: configure
  script:
   - mkdir build
   - cd build
   - conan install ..
   - cmake .. -DCMAKE_BUILD_TYPE=Release
  artifacts:
    paths:
     - build

buildstuff:
  stage: build
  script:
   - cd build
   - conan install ..
   - cmake --build . -j 2
  artifacts:
    paths:
     - build
  dependencies:
    - configurestuff

teststuff:
  stage: test
  script:
   - cd build
   - ctest . -C Release --label-exclude slow --no-label-summary
  dependencies:
    - buildstuff