image: conanio/gcc11-ubuntu16.04

before_script:
    - conan remote add gitlab ${CI_API_V4_URL}/projects/10/packages/conan
    - conan user gitlab+deploy-token-2 --remote gitlab -p ${CI_JOB_TOKEN}

stages:
  - configure
  - build
  - test

configurestuff:
  stage: configure
  script:
   - mkdir build
   - cd build
   - conan install ..
   - cmake ..
  artifacts:
    paths:
     - build

buildstuff:
  stage: build
  script:
   - cd build
   - conan install ..
   - cmake --build . -j 8
  artifacts:
    paths:
     - build
  dependencies:
    - configurestuff

teststuff:
  stage: test
  script:
   - cd build/bin
   - ./advent-of-code-core-test ~[slow]  
   - ./advent-of-code-year2015-test ~[slow]
   - ./advent-of-code-year2016-test ~[slow]
   - ./advent-of-code-year2017-test ~[slow]
   - ./advent-of-code-year2018-test ~[slow]
   - ./advent-of-code-year2019-test ~[slow]
   - ./advent-of-code-year2020-test ~[slow]
   - ./advent-of-code-year2021-test ~[slow]
  dependencies:
    - buildstuff