image: zeno15/zeno-engine-build-container

before_script:
    - cmake --version
    - conan --version
    - conan remote add gitlab ${CI_API_V4_URL}/projects/10/packages/conan
    - conan search zeno* -r gitlab
    - conan user ZENO_ENGINE_DEPLOY_TOKEN --remote gitlab -p $ZENO_ENGINE_DEPLOY_TOKEN_PASSWORD
    - conan search zeno* -r gitlab

stages:
  - configure
  - build
  - test

configurestuff:
  stage: configure
  script:
   - mkdir build
   - cd build
   - conan install .. --build=glfw --build=zeno-engine
   - conan install ..
   - cmake .. -DCMAKE_BUILD_TYPE=Release
  artifacts:
    paths:
     - build

buildstuff:
  stage: build
  script:
   - cd build
   - conan install ..
   - cmake --build . -j 2
  artifacts:
    paths:
     - build
  dependencies:
    - configurestuff

teststuff:
  stage: test
  script:
   - cd build
   - ctest . -C Release --label-exclude slow --no-label-summary
  dependencies:
    - buildstuff