image: gcc

before_script:
    - apt-get update
    - apt-get -y install cmake
    - apt-get -y install python3 python3-pip
    - pip install conan

stages:
  - build

buildstuff:
  stage: build
  script:
   - mkdir build
   - cd build
   - conan install ..
   - ls -R
   - cmake ..
   - cmake --build .
   - ls -R
   - ctest . -C Debug